# Install dependencies
install:
	pip3 install -r requirements.txt

# Install kernel environment
#install-kernel
#	python3 -m ipykernel install --user --name llava-env --display-name "Python3 (.venv Llava)"

